// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepoUrlShortener is an autogenerated mock type for the RepoUrlShortener type
type RepoUrlShortener struct {
	mock.Mock
}

// GetOriginalUrlByShort provides a mock function with given fields: ctx, shortURL
func (_m *RepoUrlShortener) GetOriginalUrlByShort(ctx context.Context, shortURL string) (string, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalUrlByShort")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShortByOriginal provides a mock function with given fields: ctx, originalURL
func (_m *RepoUrlShortener) GetShortByOriginal(ctx context.Context, originalURL string) (string, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for GetShortByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUrl provides a mock function with given fields: ctx, originalURL, shortURL
func (_m *RepoUrlShortener) SaveUrl(ctx context.Context, originalURL string, shortURL string) error {
	ret := _m.Called(ctx, originalURL, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for SaveUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, originalURL, shortURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepoUrlShortener creates a new instance of RepoUrlShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoUrlShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoUrlShortener {
	mock := &RepoUrlShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
